### ISSUE TITLE
TSA usage in Jarsign

### ISSUE THREAD

**Issue by sabre1041** [sigstore/sigstore-maven-plugin#120]
**Description**

The `jarsign` goal contains functionality for integrating with an existing Trusted Timestamp Authority. However, there appears to be several issues with the existing integration:

* Functionality enablement - In the current implementation, TSA integration is never enabled. This is due to the [existing logic](https://github.com/sigstore/sigstore-maven-plugin/blob/main/src/main/java/dev/sigstore/plugin/JarSign.java#L467) which checks to see if the `tsaUR` is blank. As the Mojo parameter has a default value define, this logic will never be triggered. In addition, the logic seems backwards and should enable the functionality only when the `tsaUR` is not blank.
* Default TSA URL - Rekor no longer provides a TSA service which results in a 404 error when using the default values.

## Proposed solutions

To address the above concerns, the following are a set of steps that can be used to not only remove any existing issues, but provide proper supportability for integrating a TSA into Jar siging:

1. Correct the logic to enable TSA functionality only when the `tsa-url` is not blank
2. As Rekor no longer exposes a TSA service, remove the `defaultValue` option from the `tsa-url` property as no TSA service is being provided by the Sigstore project and it is up to the consumer for which external solution they would like to use.

**Version**

Main branch (1.0-SNAPSHOT)

**Comment by hboutemy** [comment]
fixed in #121 thanks
