### ISSUE TITLE
Could not find artifact dev.sigstore:sigstore-maven-plugin:jar:1.0-SNAPSHOT

### ISSUE THREAD

**Issue by thomasleplus** [sigstore/sigstore-maven-plugin#89]
**Question**

Hi,

I was hoping to give this plugin a try but after I add the plugin to my [pom.xml](https://github.com/leplusorg/ristretto/blob/sigstore/pom.xml), I get the following error from Maven:

> org.apache.maven.plugin.PluginResolutionException: Plugin dev.sigstore:sigstore-maven-plugin:1.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact dev.sigstore:sigstore-maven-plugin:jar:1.0-SNAPSHOT

Is the plugin snapshot published to Maven Central? 

Also the link to the [documentation](https://sigstore.github.io/sigstore-maven-plugin/sign-mojo.html) in the [README.md](https://github.com/sigstore/sigstore-maven-plugin/blob/main/README.md) file is broken FYI.

Cheers,

Tom

**Comment by hboutemy** [comment]
0.4.0 release is now done #134 
everybody can use it, like us #137 
remember that there are known limitations: i hope we'll manage to removing these soon
